import type { Metadata } from "next";
import "./globals.css";
import Script from "next/script";
import { DevNav } from "@/components/__dev__/DevNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"font-sans"}>
        <Script
          strategy="beforeInteractive"
          src={`https://oapi.map.naver.com/openapi/v3/maps.js?ncpClientId=${process.env.NAVER_MAP_CLIENT_ID}`}
        />
        {children}
        <DevNav />
      </body>
    </html>
  );
}
